### ISSUE TITLE
Add Script Extensions

### ISSUE THREAD

**Issue by dtzar** [Azure/terraform-azurerm-compute#15]
Add Linux and Windows VM script extensions.  Due to limitations with HCL (i.e. https://github.com/hashicorp/terraform/issues/15605), this means that we'd now have a fairly crazy matrix of duplicated code to support (we're already at 4 blocks (win/Linux and then w or w/o data disks) - so I'd like to wait until this is resolved so we can optimize the code.

**Comment by kewalaka** [comment]
what about breaking this out into distinct modules, perhaps one for win & one for linux.  I've thought already that the data disks probably make more sense outside of the VM module - what if you want more than one?  I was also wondering whether it would be better to have the logic that deals with multiple machines appended 0,1,2,3 etc moved to a parent module, because at the moment you can't be (clearly) prescriptive about what you want the VM to be called, even if you create an individual machine it is currently appended with '0'.

Throwing ideas around at the moment, I'm playing around with this so keen for comment as I'm sure some of this has been considered and I may be overlooking lessons learnt already!

**Comment by lonegunmanb** [comment]
I'm closing this issue since we've supported `azurerm_virtual_machine_extension` for this module, please feel free to reopen it if you have any further question. Thanks.
