### ISSUE TITLE
Migrate away from azurerm_virtual_machine and use azurerm_linux_virtual_machine for linux and azurerm_windows_virtual_machine for windows

### ISSUE THREAD

**Issue by jack1902** [Azure/terraform-azurerm-compute#176]
Currently, the module uses azurerm_virtual_machine with a `vm-linux` and `vm-windows` approach but post `2.x` `azurerm_virtual_machine ` will be removed and is currently in a feature frozen state.

It would be great to migrate away from the deprecated and feature-frozen resource as soon as possible to reduce technical debt incurred by using it in new environments.

relates_to: https://github.com/Azure/terraform-azurerm-compute/issues/148

**Comment by lonegunmanb** [comment]
Since this module used `count`, if we migrate from `count` to `for_each` then there is no way for our existing users to upgrade the module's version without running a lot of `terraform import`.

I will create a new module for virtual machine which would use "modern" resource like `azurerm_linux_virtual_machine` and `for_each`, I'd like to introduce this feature in that new module. I'll leave this issue open until I've implemented it in the new module.

**Comment by lonegunmanb** [comment]
An update @jack1902, I've created a [new parallel module](https://github.com/lonegunmanb/terraform-azurerm-virtual-machine), still polishing it, it would be nice if we could get some feedbacks from this community.

**Comment by lonegunmanb** [comment]
I'm closing this issue since we've migrated [new module](https://github.com/Azure/terraform-azurerm-virtual-machine) to Azure organization, any further issue could be raised there. Thanks for your participating folks!
