### ISSUE TITLE
Error downloading modules os

### ISSUE THREAD

**Issue by siddrab** [Azure/terraform-azurerm-compute#80]
- Terraform Version: v0.11.8
- OS Version: Windows 10

Bug description:
Unable to complete terraform init when running from Visual code

Steps to reproduce:

1. Clone this directory from Github
2. Open the folder and run Terraform Init

$ terraform initddrive/terraform_dev"
Initializing modules...
- module.os
  Getting source "./os"
Error downloading modules: Error loading modules: error downloading 'file:///home/****/os': symlink /homehome/****/os'
.terraform/modules/e51eb6e38c3c54f01659bc97b7af1698: operation not supported

**Comment by pronictbelgium** [comment]
Dear, What is the status? I have the same issue when using the module.

**Comment by JunyiYi** [comment]
Hi @siddrab @pronictbelgium , thanks for reporting the issue. The error here is not caused by our module, it is a bug in terraform core.

One possible solution is to remove `.terraform` directory completely and run `terraform init` again.

If it is still not solved, please create a issue in terraform core just like this one: https://github.com/hashicorp/terraform/issues/5416.

**Comment by pronictbelgium** [comment]
Dear,

Seems that the workaround has not helped me out.
I will open a issue in terraform core.

Regards, 

Frederik Bisback
